FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /code/src
COPY requirements.txt /code/
RUN pip install --no-cache-dir -r /code/requirements.txt
COPY . /code
RUN pip install --no-cache-dir -e /code
WORKDIR /code/src/
